# GitHub Pages Configuration
title: Kay Gladen | KI-Keynote Speaker
description: Experte für Künstliche Intelligenz und Keynote Speaker für Fachveranstaltungen und Konferenzen
lang: de-DE
author: Kay Gladen

# Basic settings
url: ""
baseurl: ""
markdown: kramdown

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - assets/css/style.scss
